# Generated by Django 6.0.2 on 2026-08-20 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.topic'),
        ),
    ]
